[features]
seeds = false
[programs.localnet]
fundraise_platform = "GEK7AjSZwmrbKLkJWjhGGr8JFQ2djmmRoq4CgmoZuXJu"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "localnet"
wallet = "/home/bek/.config/solana/devnet.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
